require 'hot_view_components/manifest'

namespace :hot_view_components do
  desc "Install HotViewComponents into the app"
  task :install do
    if Rails.root.join("config/importmap.rb").exist?
      Rake::Task["hot_view_components:install:importmap"].invoke
    elsif Rails.root.join("package.json").exist?
      Rake::Task["hot_view_components:install:node"].invoke
    else
      puts "You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem."
    end
  end

  namespace :install do
    desc "Install HotViewComponents into the app with asset pipeline"
    task :importmap do
      run_install_template "with_importmap_controllers"
      run_install_template "with_sprockets_stylesheets"
    end

    desc "Install HotViewComponents into the app with node"
    task :node do
      run_install_template "with_node_controllers"
      run_install_template "with_sprockets_stylesheets"
    end
  end

  namespace :manifest do
    task :display do
      puts HotViewComponents::Manifest.generate_from(Rails.root.join("app/components"))
    end

    task :update do
      manifest =
        HotViewComponents::Manifest.generate_from(Rails.root.join("app/components"))

      File.open(Rails.root.join("app/components/index.js"), "w+") do |index|
        index.puts "// This file is auto-generated by ./bin/rails hot_view_components:manifest:update"
        index.puts "// Run that command whenever you add a new controller or create them with"
        index.puts "// ./bin/rails generate hot_view_component component_name"
        index.puts
        index.puts %(import { application } from "../javascript/controllers/application")
        index.puts manifest
      end
    end
  end
end

def run_install_template(path)
  system "#{RbConfig.ruby} ./bin/rails app:template LOCATION=#{File.expand_path("../install/#{path}.rb", __dir__)}"
end